# Generated by Django 4.2.4 on 2023-08-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
