# Generated by Django 4.2.4 on 2023-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_blog_contact_remove_post_author_delete_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(default='Nov 25, 2023', max_length=30),
        ),
    ]
