# Generated by Django 4.2.4 on 2023-11-26 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0010_personalinfo_resume_alter_blog_date_skills_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user1',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
