# Generated by Django 4.2.4 on 2023-11-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_resume_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user1',
        ),
    ]
